repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy

  - repo: https://github.com/psf/black
    rev: 24.8.0  # Use the latest version or a specific one
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: run-tests
        name: Run Django Tests
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
